# Generated by Django 3.2.6 on 2021-08-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1864, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
