# Generated by Django 3.2.6 on 2021-09-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210824_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashoutagent',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='merchant',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
