# Generated by Django 3.2.6 on 2021-10-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210929_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='pin',
            field=models.CharField(default='1111', max_length=5),
        ),
    ]
