# Generated by Django 3.2.6 on 2021-08-24 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210824_1320'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmoney',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', to_field='user'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clientuser', to_field='mobile'),
        ),
        migrations.AlterField(
            model_name='cashout',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.cashoutagent', to_field='user'),
        ),
        migrations.AlterField(
            model_name='cashout',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', to_field='user'),
        ),
        migrations.AlterField(
            model_name='moneytransfer',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='accounts.customer', to_field='user'),
        ),
        migrations.AlterField(
            model_name='moneytransfer',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='accounts.customer', to_field='user'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', to_field='user'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.merchant', to_field='user'),
        ),
    ]
