# Generated by Django 3.2.6 on 2021-10-11 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_clientuser_pin'),
        ('transactions', '0002_auto_20210824_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_type', models.CharField(choices=[('Send Money', 'SEND'), ('Receive Money', 'RECEIVE'), ('Bill Payment', 'BILLPAY'), ('Mobile Recharge', 'RECHARGE'), ('Add Money', 'ADDMONEY')], max_length=100)),
                ('translation_id', models.CharField(max_length=100)),
                ('amount', models.FloatField(default=0)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='accounts.clientuser')),
            ],
        ),
    ]
